sonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
sonar.projectName=Recipe Application
sonar.projectVersion=1.0

sonar.sources=backend/recipe-service/src/main/java,frontend/recipe/src
sonar.tests=backend/recipe-service/src/test/java,frontend/recipe/src

sonar.java.binaries=backend/recipe-service/target/classes
sonar.java.test.binaries=backend/recipe-service/target/test-classes
sonar.java.libraries=backend/recipe-service/target/dependency/*.jar


sonar.javascript.lcov.reportPaths=frontend/recipe/coverage/lcov.info
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=backend/recipe-service/target/site/jacoco/jacoco.xml

sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.test.ts,**/target/**,**/build/**
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts,**/*Test.java

sonar.sourceEncoding=UTF-8