name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  BACKEND_DIR: backend/recipe-service
  FRONTEND_DIR: frontend/recipe
  YC_REGISTRY_ID: crpogsfdi7ukhk7uooeg

jobs:
  # ЭТАП 1: Тесты Backend
  backend-test:
    uses: ./.github/workflows/backend-test.yml

  # ЭТАП 2: Сборка Backend
  backend-build:
    needs: backend-test
    uses: ./.github/workflows/backend-build.yml

  # ЭТАП 3: Тесты Frontend
  frontend-test:
    needs: backend-build
    uses: ./.github/workflows/frontend-test.yml

  # ЭТАП 4: Сборка Frontend
  frontend-build:
    needs: frontend-test
    uses: ./.github/workflows/frontend-build.yml

  # ЭТАП 5: SonarQube
  sonarqube-scan:
    needs: frontend-build
    uses: ./.github/workflows/sonarqube-scan.yml
    secrets: inherit

  # ЭТАП 6: Docker Backend
  docker-backend:
    needs: sonarqube-scan
    uses: ./.github/workflows/docker-backend.yml
    secrets: inherit

  # ЭТАП 7: Docker Frontend
  docker-frontend:
    needs: docker-backend
    uses: ./.github/workflows/docker-frontend.yml
    secrets: inherit

  # Этап 8: Обновление манифестов
  update-manifests:
    needs: docker-frontend
    uses: ./.github/workflows/update-manifest.yml
    secrets: inherit